[galaxie greek mnemonic] Add rules mitigating NFD characters
keymanapp/keyboards pull request #1276
Opened 2020-07-07 08:35 UTC by MakaraSok

Rules mitigating NFD for characters with:
- single diacritic
- double diacritic
- triple diacritic

Version number and year of copyrights bumped.

Fixing: https://github.com/keymanapp/keyboards/issues/1264

2020-07-07 09:07 UTC, MakaraSok commented
@AndreasJoswig Fixes have been made, but there is an issue with some characters which are, for some reason, not visible in FLEx field. It however is visible in the preview panel in the highlighted circle (see the screenshot below). The pattern is that this behavior usually happens to characters with `macron`,  `breve`, a combination of `diaeresis` and `circumflex accent`, and when `iota subscript` is present in characters with multiple diacritics.
![image](https://user-images.githubusercontent.com/28331388/86755276-b6417c00-c06b-11ea-9172-28d92bbe9a29.png)


Now, could you please test the fixes and see if you encounter the known issue above?

Here is the [keyboard package](https://drive.google.com/file/d/1XzGB0-maz0y4gsCInb6eCJ9IkV0kLuwR/view?usp=sharing) for testing.

2020-07-07 12:54 UTC, MakaraSok commented
@AndreasJoswig Thank you for the prompt response. It is great that you didn't encounter any issue. Could you let me know what your FLEx and Keyman version are?

2020-07-07 13:19 UTC, AndreasJoswig commented
@MakaraSok It is FLEx 9.0.9.0 RC under Windows 10, and Keyman 13.0.109.0

2020-07-07 13:28 UTC, LornaSIL commented
If you've turned this into an NFC keyboard I'd rather the comment in HISTORY.md clearly say that. Also, the readme.htm should say it is an NFC keyboard and the description in the keyboard_info should say that.

Also, it seems significant enough that the version should be 3.3 (not 3.2.2).

2020-07-07 21:10 UTC, mcdurdin commented
> If you've turned this into an NFC keyboard I'd rather the comment in HISTORY.md clearly say that. Also, the readme.htm should say it is an NFC keyboard and the description in the keyboard_info should say that.

The keyboard is still generating NFC -- this hasn't changed. This PR is making the keyboard more compatible with FLEx by adding rules to match NFD context.

2020-07-07 21:12 UTC, mcdurdin commented on release/g/galaxie_greek_mnemonic/source/help/galaxie_greek_mnemonic.php
> +					Version 3.2.2 released 6 Jul 2020. Add rules to mitigate NFD issues.<br/>
```suggestion
                	Version 3.3 released 6 Jul 2020. Add rules to mitigate NFD contextual matches and improve compatibility with FLEx.<br/>
```

2020-07-08 08:19 UTC, MakaraSok commented on release/g/galaxie_greek_mnemonic/source/help/galaxie_greek_mnemonic.php
> +					Version 3.2.2 released 6 Jul 2020. Add rules to mitigate NFD issues.<br/>
Changed will be added in the next commit.

2020-07-08 10:07 UTC, MakaraSok commented
> So, I repeat, I can recreate the success reported by Makara, but I cannot recreate the problem reported by him. All is well.

I tested this again in FLEx 9.0.9 using Charis SIL font with Graphite enabled and everything is OK. No error as you pointed out. :)

2020-07-13 18:53 UTC, LornaSIL commented
@mcdurdin were you going to check this or do I need to?

2020-07-13 19:22 UTC, mcdurdin commented
> @mcdurdin were you going to check this or do I need to?

I won't have time for a week or so to check -- but can do next week. Ideally, I would like to see regression tests added for the new rules.

2020-09-17 17:06 UTC, DavidLRowe commented
@mcdurdin Are you waiting for regression tests to be added before reviewing this?

2020-09-20 23:19 UTC, mcdurdin requested changes
Apologies for the long delay in reviewing this. I have carefully checked the decomposed rules and all are correct bar one, I think!

2020-12-15 03:36 UTC, MakaraSok commented
I've just got back to this. Even with FLEx 9.0.8.0, the keyboard output the expected characters both in the field and preview pain without any issue.

2020-12-15 03:36 UTC, closed without merging

2020-12-15 21:28 UTC, LornaSIL commented
@MakaraSok why was this closed?

2020-12-16 03:54 UTC, MakaraSok commented
The issue can no longer be repro-ed.

2020-12-16 16:20 UTC, LornaSIL commented
Ok. I hope you weren't using your modified keyboard that isn't in the repo!

2020-12-17 01:59 UTC, MakaraSok commented
Details on the test that proves it works as expected:

- Keyman version: 14.0.204-alpha
- Keyboard name: [Galaxie Greek (Mnemonic)](https://keyman.com/keyboards/galaxie_greek_mnemonic) 
- Keyboard version: 3.2.1
- Windows Version: Windows 10 Pro 1909 x64
- FLEx version: 9.0.8.0 RC x64

![image](https://user-images.githubusercontent.com/28331388/102432590-f6a71c00-4045-11eb-9c41-cb182891412a.png)