[xinaliq] Add s-cedilla
keymanapp/keyboards pull request #1698
Opened 2021-12-04 02:37 UTC by darcywong00

Fixes #1696

* Add s-cedilla to the <kbd>s</kbd> key rota
* Remove stray `q` longpress keys on the <kbd>Shift</kbd> button in the default layer of the touch layout
* Use canonical tag `kjj` instead of `kjj-Latn`
* Fix formatting on welcome page

@KenK-3-21 - Can you clarify if "brother" is spelled with the composing circumflex before "ss"?

2021-12-16 16:40 UTC, LornaSIL commented
@KenK-3-21 I can approve this if you can verify @darcywong00 question about above spelling of "brother".

2021-12-16 20:48 UTC, KenK-3-21 commented
Hi, Lorna,

Glad you asked. I looked over the various texts and I have found that the
spelling is ̂ssı is attested in published dictionaries, Ganieva 1994, and
Rind-Pawlowski, et al 2016. I think it is still a contested spelling in our
translation, however. I see that one translator is spelling it ŝısı.

Blessings, Ken

On Thu, Dec 16, 2021, 10:40 Lorna Evans ***@***.***> wrote:

> @KenK-3-21 <https://github.com/KenK-3-21> I can approve this if you can
> verify @darcywong00 <https://github.com/darcywong00> question about above
> spelling of "brother".
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/keymanapp/keyboards/pull/1698#issuecomment-995987668>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABVS77UAV623WEKRJZ5ARELURIJARANCNFSM5JLBGMCQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2021-12-16 21:04 UTC, LornaSIL commented
Thanks @KenK-3-21 . Does that mean the keyboard still needs adjusting?

2021-12-16 21:13 UTC, KenK-3-21 commented
Hi Lorna,
I think Darcy added the s with cedilla to the keyboard, and was waiting for
confirmation that ŝsı is a legitimate spelling.
I think the adjustment which needs to be made is that the character
"U+015D: Latin Small Letter S With Circumflex" is used in both instances.
Thanks, Ken



On Thu, Dec 16, 2021 at 3:04 PM Lorna Evans ***@***.***>
wrote:

> Thanks @KenK-3-21 <https://github.com/KenK-3-21> . Does that mean the
> keyboard still needs adjusting?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/keymanapp/keyboards/pull/1698#issuecomment-996192607>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABVS77V5FYRQTHS4WNPQIELURJH6RANCNFSM5JLBGMCQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2021-12-16 22:04 UTC, LornaSIL commented
I'm just confused about whether the **keyboard** itself is correct and something still needs fixing in the lexical model (which is a separate issue). I'll just leave this until I get more clarification.

2022-01-24 17:47 UTC, KenK-3-21 commented on release/x/xinaliq/source/xinaliq.kmn
> -'̂ss' + 's' > 's'            c reverts to base character 's'
Let's delete line 162 ...'̂ss' + 's' > 's'            c reverts to base character 's'. This is not attested in actual use.

2022-01-24 17:50 UTC, KenK-3-21 commented on release/x/xinaliq/source/xinaliq.kmn
> +'̂ss' + 's' > 'ş'            c cedilla 's'
Let's change it to '̂s' + 's' > 'ş'            c "circumflex s" changes to s with cedilla

2022-01-24 17:53 UTC, KenK-3-21 commented on release/x/xinaliq/source/xinaliq.kmn
>  'Ŝ' + 'S' > '̂SS'           C CIRCUMFLEX 'S' AND 'S'
Okay, so let's also delete this line (210).  'Ŝ' + 'S' > '̂SS'           C CIRCUMFLEX 'S' AND 'S'
Let's retain 'Ŝ' + 'S' > '̂Ş' C CIRCUMFLEX 'S' AND 'S' BECOMES S WITH CEDILLA

2022-01-24 17:56 UTC, KenK-3-21 requested changes
Let's delete line 162 ...'̂ss' + 's' > 's' c reverts to base character 's'. Let's change it to '̂s' + 's' > 'ş' c "circumflex s" changes to s with cedilla...
Okay, so let's also delete this line (210). 'Ŝ' + 'S' > '̂SS' C CIRCUMFLEX 'S' AND 'S'
Let's retain 'Ŝ' + 'S' > '̂Ş' C CIRCUMFLEX 'S' AND 'S' BECOMES S WITH CEDILLA

2022-01-24 22:26 UTC, DavidLRowe commented
@darcywong00 Do you have the information you need to update this keyboard?

2022-01-24 23:16 UTC, darcywong00 commented on release/x/xinaliq/source/xinaliq.kmn
>  'Ŝ' + 'S' > '̂SS'           C CIRCUMFLEX 'S' AND 'S'
So to confirm, if we use
```suggestion
'Ŝ' + 'S' > '̂Ş' C CIRCUMFLEX 'S' AND 'S' BECOMES S WITH CEDILLA
```
then we also delete l. 211
```
'̂SS' + 'S' > 'Ş' C CEDILLA 'S'
```

2022-01-24 23:56 UTC, darcywong00 commented on release/x/xinaliq/source/xinaliq.kmn
>  'Ŝ' + 'S' > '̂SS'           C CIRCUMFLEX 'S' AND 'S'
@DavidLRowe - Once I've confirmed about removing '̂SS' I can make the updates along with the documentation.

2022-01-31 04:33 UTC, darcywong00 commented on release/x/xinaliq/source/xinaliq.kmn
>  'Ŝ' + 'S' > '̂SS'           C CIRCUMFLEX 'S' AND 'S'
> Let's retain 'Ŝ' + 'S' > '̂Ş' C CIRCUMFLEX 'S' AND 'S' BECOMES S WITH CEDILLA

@KenK-3-21 - Can you confirm you want the output to be CIRCUMFLEX 'S' WITH CEDILLA? (That's what you're outputting `> '̂Ş'`

2022-01-31 18:31 UTC, KenK-3-21 commented on release/x/xinaliq/source/xinaliq.kmn
>  'Ŝ' + 'S' > '̂SS'           C CIRCUMFLEX 'S' AND 'S'
No, I don't want CIRCUMFLEX 'S' WITH CEDILLA... Sorry... I didn't notice the circumflex at first...that appears to have been an artifact of copying to the buffer... I want it to be like this:  'Ŝ' + 'S' >'Ş'. The next line should be 'Ş' + 'S' > 'S'. Does that make sense? Thanks for asking for confirmation!!!

2022-01-31 21:30 UTC, darcywong00 commented on release/x/xinaliq/source/xinaliq.kmn
>  'Ŝ' + 'S' > '̂SS'           C CIRCUMFLEX 'S' AND 'S'
OK, the latest commit has that rotation

2022-01-31 21:42 UTC, DavidLRowe commented
@darcywong00 Is this keyboard change ready for review?

2022-01-31 21:53 UTC, darcywong00 commented
@DavidLRowe - I think I've addressed the remaining comments, so this should be ready to review.

2022-02-02 19:16 UTC, LornaSIL approved these changes
LGTM

2022-02-02 19:23 UTC, merged