feat(sil_euro_latin): add Caps Lock and Start-of-Sentence detection
keymanapp/keyboards pull request #1908
Opened 2022-07-05 03:50 UTC by mcdurdin

Caps Lock and Start-of-Sentence detection are new features for touch devices in Keyman 15.0. The compiled keyboard remains backwardly compatible with older versions of Keyman, as access to the new functionality will just be ignored (this is known as progressive enhancement). However, the keyboard must be built with the 15.0 compiler.

In order to test the new functionality, ensure you are running Keyman 15.0.265 or later.

2022-07-05 22:38 UTC, mcdurdin commented
> Just in case, I would like to see a user test against Keyman 14 as well as 15.

* [sil_euro_latin.zip](https://github.com/keymanapp/keyboards/files/9050066/sil_euro_latin.zip)

The .kmp file within the above zip contains the changes in this PR, built with kmcomp 15.0.265. I am testing against Keyman 14 and 15 for Android currently, and will test on iOS shortly.

2022-07-05 23:09 UTC, mcdurdin commented
I have tested on:

* Keyman for Windows 14.0.294 - no issues encountered
* Keyman for Windows 15.0.265 - no issues encountered
* Keyman for Android 14.0.294 - no issues encountered, no change in behaviour from previous version
* Keyman for Android 15.0.265 - Caps Lock and Start-of-sentence on touch working well

2022-07-06 04:01 UTC, jahorton requested changes

2022-07-06 04:01 UTC, jahorton commented on release/sil/sil_euro_latin/source/sil_euro_latin.kmn
> +    any(sentencePunctuation) any(whitespace) any(whitespace) any(whitespace) > layer('shift')
Turns out that we'll need a few extra rules here due.  Without loss of generality...

```
any(sentencePunctuation) dk(1) any(whitespace) > layer('shift')
c and extra whitespace variants.
```

Why?

https://github.com/keymanapp/keyboards/blob/919dfff5b8a938bf1784bf6dce19b9a51b8dcac0/release/sil/sil_euro_latin/source/sil_euro_latin.kmn#L34

https://github.com/keymanapp/keyboards/blob/919dfff5b8a938bf1784bf6dce19b9a51b8dcac0/release/sil/sil_euro_latin/source/sil_euro_latin.kmn#L269

When an external keyboard is used on a touch device, there will be an interfering deadkey after the `'.'`.

Unless, _of course_, if the user typed the period key twice in a row:

https://github.com/keymanapp/keyboards/blob/919dfff5b8a938bf1784bf6dce19b9a51b8dcac0/release/sil/sil_euro_latin/source/sil_euro_latin.kmn#L261

2022-07-06 04:07 UTC, jahorton commented on release/sil/sil_euro_latin/source/sil_euro_latin.kmn
> +    any(sentencePunctuation) any(whitespace) any(whitespace) any(whitespace) > layer('shift')
This was bugging me when testing https://github.com/keymanapp/keyman/pull/6901, as I thought I had a weird bug remaining on my end.  Took a deep drill down to note that there was a deadkey in the way... which led me to the analysis above.

2022-07-07 04:03 UTC, jahorton commented on release/sil/sil_euro_latin/source/sil_euro_latin.kmn
> +c store(&KMW_EMBEDJS) 'sil_euro_latin_js.txt'
Is this part intentional?  Wouldn't this eliminate the custom 'help'-style desktop OSK?

2022-07-07 04:36 UTC, mcdurdin commented on release/sil/sil_euro_latin/source/sil_euro_latin.kmn
> +c store(&KMW_EMBEDJS) 'sil_euro_latin_js.txt'
oops.

2022-07-12 05:00 UTC, merged