feat: Add tool to generate gesture table
keymanapp/keyboards pull request #2594
Opened 2024-03-07 01:34 UTC by darcywong00

Addresses #2213

This adds a gestureChart tool to document gestures in a touch layout as a Markdown table. Future TODO is incorporating the Markdown table into the welcome.htm / .php help docs.

As of 17.0, gestures can be:
* longpress
* flicks
* multitap

## Usage
```
node gestureChart.js -k <keyboard>
    -k, --keyboard <full path to keyboard directory>
```

Sample output:
[sil_ipa-tablet (current).md](https://github.com/keymanapp/keyboards/files/14517501/sil_ipa-tablet.current.md)

[sil_ipa-tablet (gestures).md](https://github.com/keymanapp/keyboards/files/14517511/sil_ipa-tablet.gestures.md)
sil_ipa incorporating gestures from #2521

2024-03-07 01:41 UTC, darcywong00 commented on tools/gestureChart/gestureChart.ts
> +    console.warn(`id ${id} doesn't start with U_`);
Looking up text from a [T_XXXX] key in the .js keyboard file is an extra complexity

2024-03-07 10:45 UTC, mcdurdin requested changes
This is a useful tool. However, we don't want to start putting tooling into the keyboards repository, because this is really a Developer tool.

So, we need to move the tool to keymanapp/keyman, and ideally we will integrate this into kmc as a kmc module. Then we could merge it in 18.0.

If that sounds like too much work for now, then feel free to put it into its own repo -- just we shouldn't keep it in keyboards repo.

One other challenge is that while this tool generates Markdown, we don't currently support Markdown in keyboard documentation welcome.htm, which is where this content belongs (not just on help.keyman.com).

The whole Markdown documentation proposal can be followed in https://github.com/keymanapp/keyman/issues/9477

2024-03-07 10:45 UTC, mcdurdin commented on tools/gestureChart/gestureChart.ts
> +      text += key.text.replaceAll('|', '&#124;');
This will not work with `x|` or things like that. Nor `|*`. We need to do replacements on the whole string. There's actually a `escapeMarkdownChar` function in Developer which should do what is needed:

https://github.com/keymanapp/keyman/blob/5062bbad984760a40e5ee3d012b65d54d805db1d/developer/src/common/web/utils/src/markdown.ts#L2-L21

2024-03-07 10:45 UTC, mcdurdin commented on tools/gestureChart/gestureChart.ts
> +    console.warn(`id ${id} doesn't start with U_`);
It's also not needed -- we don't support inferring text for `T_` keys in the touch layout :grin: -- so this is the correct approach I think

2024-03-08 00:52 UTC, darcywong00 commented
> This is a useful tool. However, we don't want to start putting tooling into the keyboards repository, because this is really a Developer tool.
> 
> So, we need to move the tool to keymanapp/keyman, and ideally we will integrate this into kmc as a kmc module. Then we could merge it in 18.0.
> 
> If that sounds like too much work for now, then feel free to put it into its own repo -- just we shouldn't keep it in keyboards repo.

Understood. For now, I'll move this to its own repo (so I can continue to use on an individual keyboard basis).
I'll then incorporate all these review comments as keymanapp/keyman#10965

2024-03-08 01:07 UTC, darcywong00 commented
This is moved to a separate repo (keymanapp/gestureChart) and comments to be resolved in keymanapp/keyman#10965

2024-03-08 01:07 UTC, closed without merging

2024-03-08 12:07 UTC, mcdurdin commented
Sounds great! I like this tool, and it's going to be helpful in our updated documentation approach in the future too