[staging-17.0] Update kmc to 17.0.318-beta
keymanapp/keyboards pull request #2733
Opened 2024-05-04 00:54 UTC by darcywong00

Updating kmc compiled to current beta which required the following changes
* Add fonts to .kps files (I cherrypicked 74971f28c76aa802a6a25a5a50ffee8e32a920f2 and 3e9186595bf1e58355a505003a0962593b4876d2)
* Add definitions in the release/packages/fv_all/build.sh script

2024-05-04 00:54 UTC, darcywong00 commented on release/packages/fv_all/build.sh
> +
I copied this block from the root build.sh

2024-05-04 23:59 UTC, mcdurdin requested changes
Just burushaski_girminas.kps changes that don't seem quite right

2024-05-04 23:59 UTC, mcdurdin commented on release/b/burushaski_girminas/source/burushaski_girminas.kps
> +    </File>
Not sure why these font changes (and the next changes) are in this PR? They shouldn't impact the build, but should be in a separate PR

2024-05-04 23:59 UTC, mcdurdin commented on release/packages/fv_all/build.sh
> +# TODO: remove -W
We may need a follow-up PR for this

2024-05-05 01:28 UTC, darcywong00 commented on release/b/burushaski_girminas/source/burushaski_girminas.kps
> +    </File>
If the font files are removed from kps, kmc fails with
```
burushaski_girminas.kpj - info KM05002: Building release/b/burushaski_girminas/burushaski_girminas.kpj
burushaski_girminas.kpj - error KM09002: File DejaVuSerif.ttf does not exist.
burushaski_girminas.kpj - info KM05007: release/b/burushaski_girminas/burushaski_girminas.kpj failed to build.
burushaski_girminas.kpj - info KM0500C: Project release/b/burushaski_girminas/burushaski_girminas.kpj failed to build.
```

2024-05-06 00:22 UTC, mcdurdin commented on release/b/burushaski_girminas/source/burushaski_girminas.kps
> +    </File>
You'd also need to remove the OSKFont and DisplayFont entries on ll.83-84 below, which were also added in this PR?

2024-05-06 00:27 UTC, darcywong00 commented on release/b/burushaski_girminas/source/burushaski_girminas.kps
> +    </File>
ic - they were on the cherry-pick off of master which has the fonts
https://github.com/keymanapp/keyboards/blob/9a7accf0b1a4d25d41b7ff94c812cf1083a2b016/release/b/burushaski_girminas/source/burushaski_girminas.kps#L85-L87

I'll remove from this PR then

2024-05-06 00:32 UTC, darcywong00 commented on release/b/burushaski_girminas/source/burushaski_girminas.kps
> +    </File>
But if I remove the ttf's from el_dinka.kps below, I get
```
el_dinka.kps - info KM05006: release/el/el_dinka/source/el_dinka.kps built successfully.
el_dinka.kpj - info KM05002: Building release/el/el_dinka/el_dinka.kpj
el_dinka.kpj - error KM09002: File DejaVuSans.ttf does not exist.
el_dinka.kpj - info KM05007: release/el/el_dinka/el_dinka.kpj failed to build.
```

Maybe due to this?
```xml
<WebDisplayFonts><Font Filename="DejaVuSans.ttf"/></WebDisplayFonts>     
```

2024-05-06 00:39 UTC, mcdurdin commented on release/b/burushaski_girminas/source/burushaski_girminas.kps
> +    </File>
el_dinka.kps: correct. The compiler now verifies the existence of the fonts in WebDisplayFonts and WebOSKFonts, which it didn't earlier in the alpha.

2024-05-06 00:40 UTC, mcdurdin commented on release/b/burushaski_girminas/source/burushaski_girminas.kps
> +    </File>
> I'll remove from this PR then

Make sure you add them back in to the next PR #2734!

2024-05-06 00:41 UTC, mcdurdin approved these changes
LGTM

2024-05-06 00:47 UTC, merged