[staging-17.0] Merge master from 01d485569
keymanapp/keyboards pull request #2734
Opened 2024-05-04 02:12 UTC by darcywong00

1 of x of merging master from 01d485569 into staging-17.0

When migrating info from .keyboard_info to .kps, I'm still a little unclear when a font becomes `<DisplayFont>` vs `<WebDisplayFont>`

2024-05-04 23:50 UTC, mcdurdin requested changes
A few minor tweaks needed, cheers :grin:

2024-05-04 23:50 UTC, mcdurdin commented on release/n/newa_traditional_extended/source/newa_traditional_extended.kps
> +    <FollowKeyboardVersion/>
```suggestion
    <FollowKeyboardVersion/>
    <LicenseFile>..\LICENSE.md</LicenseFile>
```

2024-05-04 23:50 UTC, mcdurdin commented on release/n/newa_traditional_extended/source/newa_traditional_extended.kps
> +    <File>
```suggestion
    <File>
      <Name>..\LICENSE.md</Name>
      <Description></Description>
      <CopyLocation>0</CopyLocation>
      <FileType>.md</FileType>
    </File>
    <File>
```

2024-05-04 23:51 UTC, mcdurdin commented on release/b/burushaski_girminas_perso_arabic/source/burushaski_girminas_perso_arabic.kps
> +    <FollowKeyboardVersion/>
```suggestion
    <FollowKeyboardVersion/>
    <LicenseFile>..\LICENSE.md</LicenseFile>
```

2024-05-05 01:15 UTC, darcywong00 commented on release/n/newa_traditional_extended/source/newa_traditional_extended.kps
> +  </Files>
```suggestion
     <File>
      <Name>..\LICENSE.md</Name>
      <Description></Description>
      <CopyLocation>0</CopyLocation>
      <FileType>.md</FileType>
    </File>
  </Files>
```

2024-05-05 01:17 UTC, darcywong00 commented on release/b/burushaski_girminas/source/burushaski_girminas.kps
>    </Files>
```suggestion
    <File>
      <Name>..\LICENSE.md</Name>
      <Description></Description>
      <CopyLocation>0</CopyLocation>
      <FileType>.md</FileType>
    </File>
  </Files>
```

2024-05-05 01:18 UTC, darcywong00 commented on release/b/burushaski_girminas_perso_arabic/source/burushaski_girminas_perso_arabic.kps
> +  </Files>
```suggestion
    <File>
      <Name>..\LICENSE.md</Name>
      <Description></Description>
      <CopyLocation>0</CopyLocation>
      <FileType>.md</FileType>
    </File>
  </Files>
```

2024-05-05 01:19 UTC, darcywong00 commented on release/bj/bj_cree_east/source/bj_cree_east.kps
> +      <Version></Version>
```suggestion
      <Version>9.1</Version>
```

2024-05-05 01:22 UTC, darcywong00 commented on release/b/burushaski_girminas_perso_arabic/burushaski_girminas_perso_arabic.kpj
> +    </File>
Removing keyboard_info from .kps

```suggestion
```

2024-05-05 01:23 UTC, darcywong00 commented on release/n/newa_traditional_extended/newa_traditional_extended.kpj
> +    </File>
```suggestion
```
Removing keyboard_info from kps

2024-05-06 00:28 UTC, mcdurdin approved these changes

2024-05-06 00:36 UTC, mcdurdin commented
> When migrating info from .keyboard_info to .kps, I'm still a little unclear when a font becomes `<DisplayFont>` vs `<WebDisplayFont>`

If .keyboard_info has a `"font"` section in a `"languages"` entry, then that turns into `<WebDisplayFonts>` in the .keyboard_info, and `"oskFont"` becomse `<WebOSKFonts>`. e.g.:

```json
  "languages": {
    "km": {
      "oskFont": {
        "family": "Khmer Busra Kbd",
        "source": [
          "khmer_busra_osk.ttf"
        ]
      },
```

becomes

```xml
<WebOSKFonts><Font Filename="khmer_busra_osk.ttf" /></WebOSKFonts>
```

`<DisplayFont>` and `<OSKFont>` data in a .kps file should not be impacted by the .keyboard_info import; these have already been defined for a few versions.

The reason the data is split out for web fonts is so that we can list multiple alternative fonts, e.g. .woff, .woff2, which the existing DisplayFont and OSKFont elements did not support.

2024-05-06 01:13 UTC, darcywong00 commented
> > When migrating info from .keyboard_info to .kps, I'm still a little unclear when a font becomes `<DisplayFont>` vs `<WebDisplayFont>`
> 
> If .keyboard_info has a `"font"` section in a `"languages"` entry, then that turns into `<WebDisplayFonts>` in the .keyboard_info, and `"oskFont"` becomse `<WebOSKFonts>`. e.g.:
> 
> ```json
>     "km": {
>       "oskFont": {
>         "family": "Khmer Busra Kbd",
>         "source": [
>           "khmer_busra_kbd.ttf"
>         ]
>       },
>       "font": {
>         "family": "Khmer Mondulkiri",
>         "source": [
>           "Mondulkiri-R.ttf"
>         ]
>       },
> ```
> 
> becomes
> 
> ```
> <WebDisplayFonts><Font Filename="Mondulkiri-R.ttf" /></WebDisplayFonts>
> <WebOSKFonts><Font Filename="khmer_busra_osk.ttf" /></WebOSKFonts>
> ```
> 
> `<DisplayFont>` and `<OSKFont>` data in a .kps file should not be impacted by the .keyboard_info import; these have already been defined for a few versions.
> 
> The reason the data is split out for web fonts is so that we can list multiple alternative fonts, e.g. .woff, .woff2, which the existing DisplayFont and OSKFont elements did not support.

gotcha
Last commit https://github.com/keymanapp/keyboards/pull/2734/commits/20d3f4289ae9956892f2192d59efac1c064304e8 was to add newa_traditional_extended `<WebDisplayFonts>` from the (removed) keyboard_info font.

2024-05-06 01:28 UTC, merged